require('base_config')
require('plugins_config')
require('lualine_config')
require('theme_config')
-- require('solarize_config')
require('coc_config')
require('treesitter_config')
require('telescope_config')
require('netrw_config')
require('mason_config')
require('lsp_config')
require('toggleterm_config')
require('mapping_config')
require('tabline_config')
require('kommentary_config')
require('nullls_config')
require('prettier_config')
